services:
  postgres:
    image: postgres:17.5
    container_name: postgres-edu
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: {}
