services:
  postgres:
    image: postgres:17.5
    container_name: postgres-edu
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbpg
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:25.6.2.5
    container_name: clickhouse-edu
    ports:
      - "28123:8123"  # HTTP порт для ClickHouse
      - "29000:9000"  # Порт для взаимодействия с базой данных
    environment:
      CLICKHOUSE_DB: dbch
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  postgres_data:
  clickhouse_data:
  clickhouse_log: